import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/Header";
import Search from "@/components/common/Search";
import ReduxProvider from "@/redux/ReduxProvider";

const RobotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

const InterSans = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Weather Today - Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${RobotoSans.className} antialiased`}>
        <ReduxProvider>
          <div className="w-full min-h-screen overflow-x-hidden bg flex flex-col items-center justify-start xl:justify-center text-white ">
            <div className="w-9/10 lg:container mx-auto py-10 lg:py-5 ">
              <Header />
              <Search />
              {children}
            </div>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
